apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: configmap-reader-binding
subjects:
  - kind: ServiceAccount
    name: k8s-gchat               # Name of the ServiceAccount
    namespace: default            # Namespace of the ServiceAccount
roleRef:
  kind: Role
  name: configmap-reader        # The Role to bind
  apiGroup: rbac.authorization.k8s.io